### ISSUE TITLE
How do I share types between host and device code?

### ISSUE THREAD

**Issue by glyh** [akhildevelops/cudaz#6]
I may try to attempt this with a common c header between zig code and cuda c code, is this the desirable way? Is there any example passing custom types? Thanks!

**Comment by akhildevelops** [comment]
Having a common c code is desirable way. Check this project string utility library for zig, it uses PCRE library but implements it's own abstraction on top of the library for zig to see.

https://github.com/liyu1981/jstring.zig/blob/main/src/pcre/pcre_binding.c

**Comment by glyh** [comment]
I still don't understand here.

Could you please provide a bare minimum example in cudaz that passes something like a c-struct between cuda device  and zig host? 

Thank you!

**Comment by akhildevelops** [comment]
I've created an example that sends custom structs to GPU for processing. https://github.com/akhildevelops/cudaz/tree/main/example/custom_type

**Comment by glyh** [comment]
Looks like not very elegant if we have to copy paste the header for now. I guess I could open a feature request issue on   implementing `#include` derivatives?

**Comment by glyh** [comment]
Looks like abs path can work for now but relative include is failing?

```cuda
#include "../c/tuple.h"
```

Something like the above will fail.

**Comment by akhildevelops** [comment]
>It panics when CUDA tries to load the kernel withcuModuleLoadData. Should this be fixed during Compiling or Loading?
Logically it should be fixed at compiling, but surprsingly it errors out while loading.

>I would like to step in to see if this can be improved but I am fairly unfamiliar with the field. Is there any more information to see what can I do?
As you pointed, yes header files can be sent to nvrtcCreateProgram, but it's not the file paths that should be passed but the whole file content.
https://stackoverflow.com/a/40087942/19483429

>BTW, for now a workaround maybe just concatenating the kernel source code at zig's side, but that seems hacky and fragile.
Yup

**Comment by adminy** [comment]
can these types be defined in zig instead?

**Comment by akhildevelops** [comment]
You can but they need to be manually written in c for the kernel.

 Whereas having types in c are easy as zig can easily parse it.
